### ISSUE TITLE
why  the norm of magnetometer calibrated isn't equal to  local Earth magnetic norm

### ISSUE THREAD

**Issue by jyzhong** [tyrex-team/benchmarks-attitude-smartphones#6]
https://github.com/tyrex-team/benchmarks-attitude-smartphones/blob/8ad1100294465251560723c3bfa4e823e9feed52/src/Calibration/Magnetometer/retrieveParametersFromMagnetometerCalibration.m#L22-L23

**Comment by ThibaudM** [comment]
I am not sure to get your question. 
The lines you point is the formula to apply to make calibrated magnetometer norm close to the theoretically Earth magnetic field norm.

**Comment by jyzhong** [comment]
Theoretically, calibrated magnetometer norm is equal to Earth magnetic field norm. Now, I calibrate my magnetometer outside, far away from magnetic disturbance, but calibrated  magnetometer norm is smaller than Earth magnetic field norm. e.g. My calibrated magnetometer norm is 35uT, but local Earth magnetic field norm is 49uT.   Is it means my calibration is wrong ?

**Comment by ThibaudM** [comment]
Which magnetometer calibration do you use?

**Comment by jyzhong** [comment]
@ThibaudM  
I use the method about  "Least Squares Ellipsoid Specific Fitting, 2004."   I found another paper: Consistent least squares fitting of ellipsoids. If i should use the second because of the noise of my magnetometer ?

**Comment by ThibaudM** [comment]
I don't know how the "Least Squares Ellipsoid Specific Fitting, 2004." works but you can use [the calibration method I used in this paper](https://github.com/tyrex-team/benchmarks-attitude-smartphones/tree/8ad1100294465251560723c3bfa4e823e9feed52/src/Calibration/Magnetometer). It's based on ellipsoid fitting. You will never remove the noise of the magnetometer. With the ellipsoid fitting you will estimate the bias in the two frames: magnetometer frame and world frame.
